spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: Sasken@12345
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: chat-service
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: live.smtp.mailtrap.io
    post: 2525
    username: api
    password: e8ecea2ad1e1cd0a747c11d7c18acec3
#  cloud:
#    gateway:
#      routes:
#        - id: message-service
#          uri: lb://message-service
#          predicates:
#            - Path=/message/**

server:
  port: 8380
  tomcat:
    max-connections: 20

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8000/eureka/"


#logging:
#  level:
#    root: debug

springdoc:
  swagger-ui:
    oauth:
      client-id: message-app

logging:
  level:
    com.netflix.discovery: OFF