spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: Sasken@12345
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081

#logging:
#  level:
#    root: debug
